language: node_js

node_js:
- stable

cache:
  directories:
  - "./node_modules"

before_script:
- npm install -g gulp-cli
- cd frontend
- npm install

script: gulp build

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r -e 'ssh -p 4444' --quiet --exclude 'frontend' --exclude 'node_modules' --exclude 'deploy_rsa.enc' --exclude 'README.md' $TRAVIS_BUILD_DIR/ floris@185.85.18.215:/var/www/declarations.svid.nl/app/declarations
  on:
    branch: master

addons:
  ssh_known_hosts: 185.85.18.215:4444

before_deploy:
- cd ../
- openssl aes-256-cbc -K $encrypted_a297503f3296_key -iv $encrypted_a297503f3296_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
